name: Node.js CI

# Trigger the workflow on push or pull request events
on: [push, pull_request]

# Define the jobs to run
jobs:
  # Job to build and test the Node.js project
  build:
    name: Build and Test
    runs-on: windows-latest

    # Define the steps for this job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Change this to the Node.js version you want to use

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      # Optional step to build your project
      - name: Build Project
        run: npm run build
