name: Rest Api Node

on:
  push:
    branches: -"main"
  pull_request:
    branches: -"main"

  jobs:
    jobs1:
      runs-on: "ubuntu-latest"
  steps:
    -name: Hello Step
     run:  echo  "Hello world"
